apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-pod
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: resources
    repoURL: https://github.com/bakhtin/argocd-sync-example.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
