apiVersion: v1
kind: Pod
metadata:
  name: pod-1
spec:
  containers:
  - name: main
    image: alpine:3.10.2
    imagePullPolicy: IfNotPresent
    command:
      - "sleep"
      - "3603"
    livenessProbe:
      exec:
        command:
        - "true"
      initialDelaySeconds: 5
      periodSeconds: 5
    readinessProbe:
      exec:
        command:
        - "true"
      initialDelaySeconds: 5
      periodSeconds: 5
  restartPolicy: Never
