apiVersion: v1
kind: Pod
metadata:
  name: pod-1
spec:
  containers:
  - name: main
    image: alpine:3.10.2
    imagePullPolicy: IfNotPresent
    command:
      - "sleep"
      - "3600"
  restartPolicy: Never
